{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.microservice.name }}-hpa
  namespace: {{ .Values.microservice.namespace }}
  labels:
    {{- include "eks-baseline.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.microservice.name }}-deployment
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }}
  {{- if and .Values.hpa .Values.hpa.behavior }}
  behavior:
    {{- toYaml .Values.hpa.behavior | nindent 4 }}
  {{- end }}  
  metrics:
    {{- if .Values.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    {{- end }}

    {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage  | default 80 }}
    {{- end }}
    {{- if .Values.customMetrics }}
    {{- toYaml .Values.customMetrics | nindent 4 }}
    {{- end }}
    
    {{- if .Values.externalMetrics }}
    {{- toYaml .Values.externalMetrics | nindent 4 }}
    {{- end }}
{{- end }}